# Generated by Django 2.0.5 on 2018-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180516_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
