# Generated by Django 2.0.5 on 2018-05-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180516_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstatus',
            old_name='text',
            new_name='name',
        ),
    ]
