# Generated by Django 2.0.5 on 2018-05-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookimage_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updated_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='bookstatus',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='bookstatus',
            old_name='updated_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_date',
            new_name='updated',
        ),
    ]
