# Generated by Django 2.0.5 on 2018-05-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20180518_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Review'),
        ),
    ]
