# Generated by Django 2.0.5 on 2018-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20180518_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
