# Generated by Django 2.0.5 on 2018-05-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order statuses'},
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='text',
            new_name='name',
        ),
    ]
