# Generated by Django 2.0.5 on 2018-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180517_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
